# Cloud Build configuration for AgroFinder
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/agrofinder:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/agrofinder:latest'
      - '.'
    timeout: 1200s

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/agrofinder:$COMMIT_SHA'
  
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/agrofinder:latest'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'agrofinder'
      - '--image'
      - 'gcr.io/$PROJECT_ID/agrofinder:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--set-env-vars'
      - 'ENVIRONMENT=production,GCS_BUCKET_NAME=agrofinder,PINECONE_INDEX_NAME=agrofinder,LOG_LEVEL=INFO'
      - '--set-secrets'
      - 'OPENAI_API_KEY=agrofinder-openai-key:latest,PINECONE_API_KEY=agrofinder-pinecone-key:latest'

images:
  - 'gcr.io/$PROJECT_ID/agrofinder:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/agrofinder:latest'

timeout: 1800s

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

